name: Create Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Create Release and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run CI checks
        run: npm run ci
        
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
        
      - name: Bump version
        id: version-bump
        run: |
          # Bump version and capture the new version
          NEW_VERSION=$(npm version ${{ github.event.inputs.version_type }} --no-git-tag-version)
          echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "version-number=${NEW_VERSION#v}" >> $GITHUB_OUTPUT
          
      - name: Update CHANGELOG
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi
          
          VERSION="${{ steps.version-bump.outputs.version-number }}"
          DATE=$(date +%Y-%m-%d)
          
          echo "# Changelog" > CHANGELOG.tmp
          echo "" >> CHANGELOG.tmp
          echo "## [$VERSION] - $DATE" >> CHANGELOG.tmp
          echo "" >> CHANGELOG.tmp
          echo "### Added" >> CHANGELOG.tmp
          echo "- New features and improvements" >> CHANGELOG.tmp
          echo "" >> CHANGELOG.tmp
          echo "### Changed" >> CHANGELOG.tmp
          echo "- Updates and modifications" >> CHANGELOG.tmp
          echo "" >> CHANGELOG.tmp
          echo "### Fixed" >> CHANGELOG.tmp
          echo "- Bug fixes" >> CHANGELOG.tmp
          echo "" >> CHANGELOG.tmp
          
          if [ -f CHANGELOG.md ] && [ "$(wc -l < CHANGELOG.md)" -gt 1 ]; then
            tail -n +2 CHANGELOG.md >> CHANGELOG.tmp
          fi
          
          mv CHANGELOG.tmp CHANGELOG.md
        
      - name: Commit and push changes
        run: |
          git add package.json CHANGELOG.md
          git commit -m "chore(release): bump version to ${{ steps.version-bump.outputs.new-version }}"
          git tag ${{ steps.version-bump.outputs.new-version }}
          git push origin main
          git push origin ${{ steps.version-bump.outputs.new-version }}
        
      - name: Build package
        run: npm run build
        
      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version-bump.outputs.new-version }}
          release_name: Release ${{ steps.version-bump.outputs.new-version }}
          body: |
            ## Changes in ${{ steps.version-bump.outputs.new-version }}
            
            This release includes various improvements and bug fixes.
            
            ### Installation
            ```bash
            npm install -g @MaelitoP/mention-mcp-server
            ```
            
            ### Usage
            ```bash
            npx @MaelitoP/mention-mcp-server
            ```
            
            See the [README](https://github.com/MaelitoP/mention-mcp-server#readme) for full documentation.
          draft: false
          prerelease: false
